name: interview_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"  # Updated for Dart 3.8.1
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  js: ^0.6.7
  universal_html: ^2.2.0
  dio: ^5.4.0  # Changed from 'any' to stable version
  logger: ^2.0.2
  google_fonts: ^6.1.0  # Changed from 'any'
  shimmer: ^3.0.0  # Changed from 'any'
  flutter_animate: ^4.5.0
  animate_do: ^4.2.0
  image_picker: ^1.1.0
  provider: ^6.1.1  # Changed from 'any'
  animated_text_kit: any
  intl: ^0.18.1  # Changed from 'any'
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  shared_preferences: ^2.2.2  # Changed from 'any'
  camera: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true